=== AlenaDziomina/GroukAlena_Task03/xml-resources/jaxb/test/equip.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://epam.by/motoequip"
        xmlns:tns="http://epam.by/motoequip"
            elementFormDefault="qualified">
        <element name="moto-equip">
            <complexType>
                <sequence>
                    <element ref="tns:moto-equipment"
                            minOccurs="1"
                            maxOccurs="unbounded"/>
                </sequence>
            </complexType>
        </element>
        
        <element name="moto-equipment" type="tns:MotoEquipment" abstract="true"></element>
        <element name="base-moto-equipment" type="tns:BaseMotoEquipment" abstract="true"></element>
        <element name="special-moto-equipment" type="tns:SpecialMotoEquipment" abstract="true"></element>
        <element name="main-equip" type="tns:MainEquip" abstract="true"></element>
        <element name="additional-equip" type="tns:AdditionalEquip" abstract="true"></element>
        <element name="body-protection" type="tns:BodyProtection" abstract="true"></element>
        <element name="built-in-body-protection" type="tns:BuiltInBodyProtection" abstract="true"></element>
        <element name="separate-body-protection" type="tns:SeparateBodyProtection" abstract="true"></element>
        <element name="helmet" type="tns:Helmet" substitutionGroup="tns:moto-equipment"></element>
        <element name="shoes" type="tns:Shoes" substitutionGroup="tns:moto-equipment"></element>
        <element name="jacket" type="tns:Jacket" substitutionGroup="tns:moto-equipment"></element>
        <element name="pants" type="tns:Pants" substitutionGroup="tns:moto-equipment"></element>
        <element name="gloves" type="tns:Gloves" substitutionGroup="tns:moto-equipment"></element>
        <element name="armor-jacket" type="tns:ArmorJacket" substitutionGroup="tns:moto-equipment"></element>
        <element name="elbow-protector" type="tns:ElbowProtector" substitutionGroup="tns:moto-equipment"></element>
        <element name="knee-protector" type="tns:KneeProtector" substitutionGroup="tns:moto-equipment"></element>
        <element name="termolinen" type="tns:Termolinen" substitutionGroup="tns:moto-equipment"></element>
        <element name="slicker" type="tns:Slicker" substitutionGroup="tns:moto-equipment"></element>
        <element name="balaclava" type="tns:Balaclava" substitutionGroup="tns:moto-equipment"></element>
        <element name="protection-insert" type="tns:ProtectionInsert" substitutionGroup="tns:moto-equipment"></element>
        <element name="sliders" type="tns:Sliders" substitutionGroup="tns:moto-equipment"></element>
        <element name="visor" type="tns:Visor" substitutionGroup="tns:moto-equipment"></element>
        
        <complexType name="MotoEquipment">
            <sequence>
                <element name="manufacturer" type="string"></element>
                <element name="price" type="positiveInteger"></element>
                <element name="weight" type="float"></element>                  
                <element name="baseMaterial" type="string"></element>
            </sequence>
            <attribute name="id" type="ID" use="required"/>
            <attribute name="name" type="string" use="required"/>
        </complexType>
        
        <complexType name="SpecialMotoEquipment">
            <complexContent>
                <extension base="tns:MotoEquipment">
                    <sequence>
                        <element name="forWhat" type="IDREF" maxOccurs="unbounded"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="BaseMotoEquipment">
            <complexContent>
                <extension base="tns:MotoEquipment">
                    <attribute name="size" type="string" use="required"/>
                    <attribute name="genderStyle" use="optional" default="Y">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Y"></enumeration>
                                <enumeration value="M"></enumeration>
                                <enumeration value="W"></enumeration>
                                <enumeration value="Ch"></enumeration>
                            </restriction>
                        </simpleType>
                    </attribute>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="MainEquip">
            <complexContent>
                <extension base="tns:BaseMotoEquipment">
                    <sequence>
                        <element name="motoType" default="COMMON">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="TURIST"></enumeration>
                                    <enumeration value="SPORT"></enumeration>
                                    <enumeration value="ENDURO"></enumeration>
                                    <enumeration value="CROSS"></enumeration>
                                    <enumeration value="STUNT"></enumeration>
                                    <enumeration value="COMMON"></enumeration>
                                </restriction>
                            </simpleType>
                        </element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="AdditionalEquip">
            <complexContent>
                <extension base="tns:BaseMotoEquipment">
                    <sequence>
                        <element name="season">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="SPRING"></enumeration>
                                    <enumeration value="SUMMER"></enumeration>
                                    <enumeration value="AUTUMN"></enumeration>
                                    <enumeration value="WINTER"></enumeration>
                                </restriction>
                            </simpleType>
                        </element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="BodyProtection">
            <complexContent>
                <extension base="tns:MainEquip">
                    <sequence>
                        <element name="protectionMaterial" type="string"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="BuiltInBodyProtection">
            <complexContent>
                <extension base="tns:BodyProtection">
                    <sequence>
                        <element name="waterproof" type="boolean"></element>
                        <element name="perforation" type="boolean"></element>
                        <element name="insulation" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="SeparateBodyProtection">
            <complexContent>
                <extension base="tns:BodyProtection">
                    <sequence>
                        <element name="mountType" type="string"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Jacket">
            <complexContent>
                <extension base="tns:BuiltInBodyProtection">
                    <sequence>
                        <element name="backInsert" type="boolean"></element>
                        <element name="elbowsInsert" type="boolean"></element>
                        <element name="shouldersInsert" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Pants">
            <complexContent>
                <extension base="tns:BuiltInBodyProtection">
                    <sequence>
                        <element name="hipInsert" type="boolean"></element>
                        <element name="kneeInsert" type="boolean"></element>
                        <element name="sliderMount" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Gloves">
            <complexContent>
                <extension base="tns:BuiltInBodyProtection">
                    <sequence>
                        <element name="palmProtect" type="boolean"></element>
                        <element name="fingersProtect" type="boolean"></element>
                        <element name="knucklesProtect" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="ArmorJacket">
            <complexContent>    
                <extension base="tns:SeparateBodyProtection">
                    <sequence>
                        <element name="backProtect" type="boolean"></element>
                        <element name="chestProtect" type="boolean"></element>
                        <element name="elbowsProtect" type="boolean"></element>
                        <element name="shouldersProtect" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>  
        </complexType>
        
        <complexType name="ElbowProtector">
            <complexContent>
                <extension base="tns:SeparateBodyProtection">
                    <sequence>
                        <element name="articulated"  type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="KneeProtector">
            <complexContent>
                <extension base="tns:SeparateBodyProtection">
                    <sequence>
                        <element name="articulated"  type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Helmet">
            <complexContent>
                <extension base="tns:MainEquip">
                    <sequence>
                        <element name="shellMaterial" type="string"></element>
                        <element name="insertMaterial" type="string"></element>
                        <element name="vents" type="positiveInteger"></element>
                        <element name="sunVisor" type="boolean"></element>
                        <element name="headsetConnector" type="boolean"></element>
                        <element name="admissionGp" type="boolean"></element>
                    </sequence>
                    <attribute name="helmetType" use="required">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="INTEGRAL"/>
                                <enumeration value="MODULAR"/>
                                <enumeration value="JET"/>
                                <enumeration value="CROSS"/>
                                <enumeration value="ENDURO"/>
                            </restriction>
                        </simpleType>
                    </attribute>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Shoes">
            <complexContent>
                <extension base="tns:MainEquip">
                    <sequence>
                        <element name="soleMaterial" type="string"></element>
                        <element name="protectionMaterial" type="string"></element>
                        <element name="mountType" type="string"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Termolinen">
            <complexContent>
                <extension base="tns:AdditionalEquip">
                    <sequence>
                        <element name="elastic" type="boolean"></element>
                        <element name="seamless" type="boolean"></element>
                    </sequence>
                    <attribute name="clothesType" use="required">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="socks"></enumeration>
                                <enumeration value="tshirt"></enumeration>
                                <enumeration value="jumper"></enumeration>
                                <enumeration value="shorts"></enumeration>
                                <enumeration value="pants"></enumeration>
                            </restriction>
                        </simpleType>
                    </attribute>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Slicker">
            <complexContent>
                <extension base="tns:AdditionalEquip">
                    <sequence>
                        <element name="separate" type="boolean"></element>
                        <element name="fluorescent" type="boolean"></element>
                        <element name="hood" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Balaclava">
            <complexContent>
                <extension base="tns:AdditionalEquip">
                    <sequence>
                        <element name="seamless" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="ProtectionInsert">
            <complexContent>
                <extension base="tns:SpecialMotoEquipment">
                    <attribute name="bodyPart" use="required">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="back"></enumeration>
                                <enumeration value="elbows"></enumeration>
                                <enumeration value="shoulders"></enumeration>
                                <enumeration value="chest"></enumeration>
                                <enumeration value="hip"></enumeration>
                                <enumeration value="knee"></enumeration>
                            </restriction>
                        </simpleType>
                    </attribute>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Sliders">
            <complexContent>
                <extension base="tns:SpecialMotoEquipment">
                    <sequence>
                        <element name="hasPicture" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        <complexType name="Visor">
            <complexContent>
                <extension base="tns:SpecialMotoEquipment">
                    <sequence>
                        <element name="antiblick" type="boolean"></element>
                        <element name="antifog" type="boolean"></element>
                        <element name="pinlock" type="boolean"></element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        
        
        
        
        
        
        
        
        
    </schema>

=== AlenaDziomina/GroukAlena_Task03/src/task03/equip.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<moto-equip
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://epam.by/motoequip'
    xsi:schemaLocation='http://epam.by/motoequip equip.xsd'>
    
    <helmet id="id1" name="520 CARBON" size="XL" genderStyle="M" helmetType="INTEGRAL">
        <manufacturer>ROCC</manufacturer>
        <price>300</price>
        <weight>1.210</weight>
        <baseMaterial>ABS</baseMaterial>
        <motoType>COMMON</motoType>
        <shellMaterial>Carbon</shellMaterial>
        <insertMaterial>HydraDry</insertMaterial>
        <vents>7</vents>
        <sunVisor>true</sunVisor>
        <headsetConnector>false</headsetConnector>
        <admissionGp>false</admissionGp>
    </helmet>
    <helmet id="id2" name="524 FIBERGLASS" size="XL" genderStyle="Y" helmetType="INTEGRAL">
        <manufacturer>ROCC</manufacturer>
        <price>170</price>
        <weight>1.450</weight>
        <baseMaterial>ABS</baseMaterial>
        <motoType>ENDURO</motoType>
        <shellMaterial>Fiberglass</shellMaterial>
        <insertMaterial>HydraDry</insertMaterial>
        <vents>5</vents>
        <sunVisor>true</sunVisor>
        <headsetConnector>false</headsetConnector>
        <admissionGp>false</admissionGp>
    </helmet>
    <helmet id="id3" name="482 COOL" size="XL" helmetType="INTEGRAL">
        <manufacturer>ROCC</manufacturer>
        <price>160</price>
        <weight>1.450</weight>
        <baseMaterial>ABS</baseMaterial>
        <motoType></motoType>
        <shellMaterial>ABS</shellMaterial>
        <insertMaterial>Silver Cool</insertMaterial>
        <vents>7</vents>
        <sunVisor>true</sunVisor>
        <headsetConnector>false</headsetConnector>
        <admissionGp>false</admissionGp>
    </helmet>
    <visor id="id4" name="sunVisor">
        <manufacturer>ROCC</manufacturer>
        <price>10</price>
        <weight>0.050</weight>
        <baseMaterial>ABS</baseMaterial>
        <forWhat>id2</forWhat>
        <forWhat>id3</forWhat>
        <antiblick>true</antiblick>
        <antifog>true</antifog>
        <pinlock>true</pinlock>
    </visor>

</moto-equip>
